module.exports = {
  // Note: config only includes the used styles & variables of your selection
  content: [
    "./index.html",
    "./src/**/*.{ts,tsx,js,jsx}",
    "./Pages/*.{ts,tsx,js,jsx}",
    "./components/**/*.{ts,tsx,js,jsx}",
  ],

  theme: {
    extend: {
      fontFamily: {
        "title-font-family": "Oswald-Bold, sans-serif",
        "subtitle-font-family": "Oswald-Regular, sans-serif",
        "link-nav-default-font-family": "NotoSans-Regular, sans-serif",
        "button-label-font-family": "NotoSans-Regular, sans-serif",
        "header-font-family": "Oswald-Bold, sans-serif",
        "subheader-font-family": "Oswald-Regular, sans-serif",
        "body-font-family": "NotoSans-Regular, sans-serif",
        "footer-header-font-family": "NotoSans-Regular, sans-serif",
        "font-family-headers": "Oswald-Bold, sans-serif",
        "font-family-subheading": "-, sans-serif",
        "font-family-body": "NotoSans-Regular, sans-serif",
      },
      fontSize: {
        "title-font-size": "48px",
        "subtitle-font-size": "36px",
        "link-nav-default-font-size": "16px",
        "button-label-font-size": "16px",
        "header-font-size": "28px",
        "subheader-font-size": "24px",
        "body-font-size": "16px",
        "footer-header-font-size": "24px",
        "font-size-3xl": "48px",
        "font-size-2xl": "36px",
        "font-size-med-base": "16px",
        "font-size-xl": "28px",
        "font-size-lg": "24px",
      },
      fontWeight: {
        "title-font-weight": "700",
        "subtitle-font-weight": "400",
        "link-nav-default-font-weight": "400",
        "button-label-font-weight": "400",
        "header-font-weight": "700",
        "subheader-font-weight": "400",
        "body-font-weight": "400",
        "footer-header-font-weight": "400",
      },
      lineHeight: {
        "title-line-height": "normal",
        "subtitle-line-height": "normal",
        "link-nav-default-line-height": "16px",
        "button-label-line-height": "normal",
        "header-line-height": "normal",
        "subheader-line-height": "normal",
        "body-line-height": "normal",
        "footer-header-line-height": "normal",
        "font-size-med-base": "16px",
      },
      letterSpacing: {
        "font-kerning-normal": "",
      },
      borderRadius: {},
      colors: {
        "footer-top-border": "#ccd2d3",
        "color-palette-primary-white": "#fcffff",
        "header-and-footer-nav-bar-background-fill": "#fcffff",
        "color-palette-brand-gold-pe-gold-5": "#fcf0db",
        "color-palette-primary-black": "#0e2225",
        "color-palette-brand-green-pe-green-4": "#c7d7ca",
        "color-palette-brand-green-pe-green-5": "#e7f0e7",
        "legislative-blue-5": "#edf2f8",
        "campaign-brown-5": "#e4d7d5",
        "campaign-brown": "#79443b",
        "header-and-footer-footer-background-fill": "#fcffff",
        "color-palette-secondary-pe-grey-4": "#ccd2d3",
        "header-and-footer-nav-bar-menu-links-default": "#316da5",
        "pe-gold-2": "#f3c271",
        "pe-gold": "#f0b34d",
        "open-source-green": "#aec0b2",
        "pe-gold-4": "#f9e1b8",
        "pe-gold-3": "#f6d194",
        "bg-pe-gold-5": "#fcf0db",
        "legislative-blue": "#588bbb",
        "header-and-footer-footer-header": "#0e2225",
        "header-and-footer-footer-body": "#0e2225",
        "color-palette-secondary-pe-grey-1": "#56696d",
        "color-palette-secondary-pe-grey-2": "#859396",
        "color-palette-seczondary-pe-grey-3": "#abb4b6",
      },
      spacing: {
        "desktop-gutter-base": "24px",
        "desktop-margin-base": "32px",
        "spacing-base-8-8": "64px",
        "spacing-base-8-6": "48px",
        "spacing-base-8-1": "8px",
        "spacing-base-8-2": "16px",
        "desktop-margin-max": "32px",
        "spacing-base-8-4": "32px",
        "spacing-base-8-25": "20px",
        "spacing-base-8-05": "4px",
      },
      width: {
        "desktop-breakpoint-base": "1280px",
        "desktop-column-width-base-col-03": "287px",
        "desktop-column-width-base-col-10": "1011px",
        "desktop-column-width-base-col-02": "183px",
        "spacing-base-8-2": "16px",
        "desktop-breakpoint-max": "2000px",
        "desktop-column-width-max-col-05": "793px",
      },
      minWidth: {},
      maxWidth: {},
      height: {
        "spacing-base-8-10": "80px",
        "spacing-base-8-4": "32px",
        "spacing-base-8-6": "48px",
        "spacing-base-8-2": "16px",
        "spacing-base-8-8": "64px",
        "desktop-column-width-base-col-03": "287px",
        "spacing-base-8-1": "8px",
      },
      minHeight: {},
      maxHeight: {},
      keyframes: {
        slideUp: {
          "0%": { opacity: "0", transform: "translateY(10px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
      },
      animation: {
        "slide-up": "slideUp 0.5s ease-out",
      },
    },
  },
};
